steps:
  # Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    args: ['init']
    
  # Validate Terraform files
  - name: 'hashicorp/terraform:latest'
    args: ['validate']
    
  # Plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    args: ['plan', '-out=tfplan']
    
  # Apply Terraform changes (with approval trigger or separate step)
  - name: 'hashicorp/terraform:latest'
    args: ['apply', 'tfplan']