steps:
  # Debug step to show working directory
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-info'
    dir: '.'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Infrastructure directory contents:"
        ls -la infrastructure/

  # Initialize Terraform
  - name: 'hashicorp/terraform:latest'
    id: 'tf-init'
    dir: 'infrastructure'
    args: ['init', '-input=false']
    
  # Validate Terraform files
  - name: 'hashicorp/terraform:latest'
    id: 'tf-validate'
    dir: 'infrastructure'
    args: ['validate']
    
  # Plan Terraform changes
  - name: 'hashicorp/terraform:latest'
    id: 'tf-plan'
    dir: 'infrastructure'
    args: ['plan', '-input=false', '-out=tfplan']
    
  # Apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    id: 'tf-apply'
    dir: 'infrastructure'
    args: ['apply', '-input=false', 'tfplan']

options:
  logging: CLOUD_LOGGING_ONLY