steps:
  # Debug step to show working directory
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'debug-info'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Current directory: $(pwd)"
        echo "Directory contents:"
        ls -la
        echo "Google Cloud credentials:"
        gcloud auth list

  # Initialize Terraform with more verbose logging
  - name: 'hashicorp/terraform:latest'
    id: 'tf-init'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        terraform init -input=false
    
  # Validate Terraform files
  - name: 'hashicorp/terraform:latest'
    id: 'tf-validate'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd infrastructure
        terraform validate
    
  # Plan Terraform changes with detailed error output
  - name: 'hashicorp/terraform:latest'
    dir: 'infrastructure'
    id: 'tf-plan'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd infrastructure
        echo "Running Terraform plan..."
        terraform plan -input=false -out=tfplan
    
  # Apply Terraform changes
  - name: 'hashicorp/terraform:latest'
    id: 'tf-apply'
    args:
      - '-c'
      - |
        terraform apply -input=false tfplan

options:
  logging: CLOUD_LOGGING_ONLY